apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  namespace: qa
  annotations:
      circleci.com/project-id: 28dc66e1-5da4-46b2-8553-075a203b79fe
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-container
        image: 1983764/my-k8s-app:qa
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      restartPolicy: Always